url := "nix run -Lv github:gtrunsec/vast2nix/"
dev := "nix run -Lv /home/gtrun/ghq/github.com/GTrunSec/vast2nix"
rev := "dd686a45ffca65350cabc3ff0be59baea16144eb"
# [ "x86-64-darwin" ]
system := "#x86_64-linux"
deploy := ".user.entrypoints.deploy --refresh --override-input lock"
config := ".user.entrypoints.config --refresh --override-input lock"

deploy arg:
     {{dev}}{{system}}{{deploy}} $PRJ_ROOT/profiles/test -- --env-file=$PRJ_ROOT/profiles/test/deploy.env -t {{arg}}

doc:
     {{dev}}{{system}}{{deploy}} $PRJ_ROOT/profiles/test -- doc

config:
     {{dev}}{{system}}{{config}} $PRJ_ROOT/profiles/test

dev-lock:
     {{url}}{{rev}}{{system}}{{config}} ./profiles/test -- doc

