dev := "nix run -Lv /home/gtrun/ghq/github.com/GTrunSec/vast2nix"
# [ "x86-64-darwin" ]
system := "#x86_64-linux"
deploy := ".user.entrypoints.deploy --refresh --override-input lock"
config := ".user.entrypoints.config --refresh --override-input lock"

deploy arg1 arg2:
    {{dev}}{{system}}{{deploy}} $PRJ_ROOT/profiles/{{arg1}} -- --env-file=$PRJ_ROOT/profiles/test/deploy.env -t {{arg2}}

config arg1 arg2:
    {{dev}}{{system}}{{config}} $PRJ_ROOT/profiles/{{arg1}} -- --env-file=$PRJ_ROOT/profiles/test/deploy.env -t {{arg2}}
